name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: "OpenZeppelin/openzeppelin-contracts"
    
      - run: npm update
      - run: npm install --save-dev @openzeppelin/contracts      
      - run: npm audit fix
      - run: npm ci
      - uses: crytic/slither-action@v0.1.1
        with:
          node-version: 16.15.0 
          solc-version: 0.8.10
          slither-args: "-solc-remaps @=node_modules/@"
